name: 'Install shinyverse packages'
description: 'Installs everything in a single pak installation step. Meant to work cross platform and R version'
author: 'Barret Schloerke'
inputs:
  r-version:
    description: R version to install
    default: release
    required: false
  extra-packages:
    description: Extra packages to install
    default: ""
    required: false
  cache-version:
    description: Cache version key to pass through
    default: "2"
    required: false
  http-user-agent:
    description: User agent to pass through
    default: ""
    required: false
  pandoc-version:
    description: Pandoc version to pass through
    default: "2.7.3"
    required: false
runs:
  using: "composite"
  steps:
    - name: Install Chinese fonts on Linux
      if: runner.os == 'Linux'
      shell: bash
      # https://unix.stackexchange.com/a/548473
      run: sudo apt-get install -y fonts-arphic-ukai fonts-arphic-uming

    - name: Install system dependencies for igraph
      if: runner.os == 'Linux'
      shell: bash
      run: sudo apt-get install -y libglpk-dev

    - name: Gather remotes and app deps
      id: shinyverse
      shell: Rscript {0}
      run: |
        source("inst/gha/gha-shinyverse-packages.R")

    - name: Rtools version
      if: runner.os == 'Windows'
      id: rtools-version
      shell: Rscript {0}
      run: |
        # Get R version like `"4.2"`
        short_r_version <- sub("\\.\\d$", "", "${{ inputs.r-version }}")
        # For R versions >= 4.2, use Rtools v42
        # Otherwise leave blank
        if (
          package_version("${{ inputs.r-version }}") >= package_version("4.2")
        ) {
          message("Using Rtools v42")
          cat("::set-output name=value::42\n", sep = "")
        } else {
          message("Not setting Rtools version!")
        }

    - name: Adjust packages to install
      id: pkgs
      shell: Rscript {0}
      run: |
        pkgs_to_install <- "${{ steps.shinyverse.outputs.packages }}"
        is_windows <- .Platform$OS.type == "windows"
        is_linux <- Sys.info()[["sysname"]] == "Linux"
        is_mac <- Sys.info()[["sysname"]] == "Darwin"
        # Get R version like `"4.2"`
        short_r_version <- sub("\\.\\d$", "", "${{ inputs.r-version }}")

        replace_or_add <- function(find_val, replace_val) {
          pkgs_to_install <<-
            if (grepl(find_val, pkgs_to_install, fixed = TRUE)) {
              sub(find_val, replace_val, pkgs_to_install, fixed = TRUE)
            } else {
              paste0(pkgs_to_install, ",", replace_val)
            }
        }

        if (is_mac) {
          switch(short_r_version,
            "3.5" = {
              # Apps 181-185
              replace_or_add(
                "any::systemfonts",
                "url::https://cran.r-project.org/src/contrib/Archive/systemfonts/systemfonts_1.0.3.tar.gz"
              )
            }
          )
        }
        if (is_linux) {
          switch(short_r_version,
            "4.2" = {
              replace_or_add("any::XML", "XML")
            },
            "3.6" = {
              replace_or_add(
                "any::rjson",
                "url::https://cran.r-project.org/src/contrib/Archive/rjson/rjson_0.2.20.tar.gz"
              )
            },
            "3.5" = {
              replace_or_add(
                "any::rjson",
                "url::https://cran.r-project.org/src/contrib/Archive/rjson/rjson_0.2.20.tar.gz"
              )
              replace_or_add(
                "any::radiant",
                "url::https://cran.r-project.org/src/contrib/Archive/radiant/radiant_1.3.2.tar.gz"
              )
            }
          )
        }
        if (is_windows) {
          switch(short_r_version,
            "3.5" = {
              replace_or_add(
                "any::mapview",
                "url::https://cran.r-project.org/bin/windows/contrib/3.5/mapview_2.7.8.zip"
              )
              replace_or_add(
                "any::sf",
                "url::https://cran.r-project.org/bin/windows/contrib/3.5/sf_0.9-2.zip"
              )

              # https://github.com/r-spatial/s2/issues/140
              # Once s2 > 1.0.7 is released, this can be removed... hopefully
              replace_or_add(
                "any::s2",
                "r-spatial/s2"
              )
            }
          )
        }
        message("Final packages:\n", gsub(",", ",\n", pkgs_to_install))
        cat("::set-output name=to-install::", pkgs_to_install, "\n", sep = "")

    - name: Install R, shinycoreci, and shinyverse
      uses: rstudio/shiny-workflows/setup-r-package@v1
      with:
        r-version: ${{ inputs.r-version }}
        cache-version: ${{ inputs.cache-version }}
        http-user-agent: ${{ inputs.http-user-agent }}
        pandoc-version: ${{ inputs.pandoc-version }}
        rtools-version: ${{ steps.rtools-version.outputs.value }}
        extra-packages:
          local::.
          ${{ steps.pkgs.outputs.to-install }}
          ${{ inputs.extra-packages }}
