name: 'Install shinyverse packages'
description: 'Installs everything in a single pak installation step. Meant to work cross platform and R version'
author: 'Barret Schloerke'
inputs:
  r-version:
    description: R version to install
    default: release
    required: false
  extra-packages:
    description: Extra packages to install
    default: ""
    required: false
  cache-version:
    description: Cache version key to pass through
    default: "2"
    required: false
  http-user-agent:
    description: User agent to pass through
    default: ""
    required: false
  pandoc-version:
    description: Pandoc version to pass through
    default: "2.7.3"
    required: false
runs:
  using: "composite"
  steps:
    - name: Install Chinese fonts on Linux
      if: runner.os == 'Linux'
      shell: bash
      # https://unix.stackexchange.com/a/548473
      run: sudo apt-get install -y fonts-arphic-ukai fonts-arphic-uming

    - name: Gather remotes and app deps
      id: shinyverse
      shell: Rscript {0}
      run: |
        source("inst/gha/gha-shinyverse-packages.R")

    - name: Rtools version
      if: runner.os == 'Windows' && startsWith('${{ inputs.r-version }}', '4.2')
      id: rtools-version
      shell: bash
      run: |
        echo "::set-output name=value::42"

    - name: Adjust packages to install
      id: pkgs
      shell: Rscript {0}
      run: |
        pkgs_to_install <- "${{ steps.shinyverse.outputs.packages }}"
        is_linux <- Sys.info()[["sysname"]] == "Linux"
        if (is_linux) {
          # Get R version like `"4.2"`
          short_version <- sub("\\.\\d$", "", as.character(getRversion()))

          replace_or_add <- function(find_val, replace_val) {
            pkgs_to_install <<-
              if (grepl(find_val, pkgs_to_install, fixed = TRUE)) {
                sub(find_val, replace_val, pkgs_to_install, fixed = TRUE)
              } else {
                paste0(pkgs_to_install, ",", replace_val)
              }
          }

          switch(short_version,
            "4.2" = {
              replace_or_add("any::XML", "XML")
            },
            "3.6" = {
              replace_or_add(
                "any::rjson",
                "url::https://cran.r-project.org/src/contrib/Archive/rjson/rjson_0.2.20.tar.gz"
              )
            },
            "3.5" = {
              replace_or_add(
                "any::rjson",
                "url::https://cran.r-project.org/src/contrib/Archive/rjson/rjson_0.2.20.tar.gz"
              )
              replace_or_add(
                "any::radiant",
                "url::https://cran.r-project.org/src/contrib/Archive/radiant/radiant_1.3.2.tar.gz"
              )
            }
          )
        }
        message("Final packages:\n", gsub(",", ",\n", pkgs_to_install))
        cat("::set-output name=to-install::", pkgs_to_install, "\n", sep = "")

    - name: Install R, shinycoreci, and shinyverse
      uses: rstudio/shiny-workflows/setup-r-package@v1
      with:
        r-version: ${{ inputs.r-version }}
        cache-version: ${{ inputs.cache-version }}
        http-user-agent: ${{ inputs.http-user-agent }}
        pandoc-version: ${{ inputs.pandoc-version }}
        rtools-version: ${{ steps.rtools-version.outputs.value }}
        extra-packages:
          local::.
          ${{ steps.pkgs.outputs.to-install }}
          ${{ inputs.extra-packages }}
