name: 'Common workflow steps'
description: 'Set windows line endings and install macOS deps'
author: 'Barret Schloerke'
inputs:
  install-macOS-deps:
    description: Should Cairo and textshaping dependencies be installed through `brew`?
    default: true
    required: false
runs:
  using: "composite"
  steps:
    # https://github.com/actions/checkout/issues/135
    - name: Set git to use LF
      if: runner.os == 'Windows'
      run: |
        git config --system core.autocrlf false
        git config --system core.eol lf

    # xquartz and cairo are needed for Cairo package.
    # harfbuzz and fribidi are needed for textshaping package.
    - name: Mac systemdeps
      if: ${{ inputs.install-macOS-deps }} && runner.os == 'macOS'
      run: |
        brew install --cask xquartz
        brew install cairo
        brew install harfbuzz fribidi
