name: Test apps

on:
  push:
    branches:
      - test**
  pull_request:
    branches:
      - main
  # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#onschedule
  # https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_16
  schedule:
    - cron: "0 5 * * 1-5" # every work night (delayed 2 hrs)
  repository_dispatch:
    types:
      - all
      # Trigger with `shinycoreci::trigger_tests()`
      - test

jobs:
  precheck:
    uses: ./.github/workflows/apps-test-precheck.yml
  config:
    needs: [precheck]
    uses: ./.github/workflows/apps-config.yml

  macos-release:
    if: ${{ ! cancelled() }}
    needs: [config, ubuntu-release]
    uses: ./.github/workflows/apps-test-os.yml
    with:
      r-version: ${{ needs.config.outputs.release }}
      os: ${{ needs.config.outputs.macos }}
      cache-version: ${{ needs.config.outputs.cache-version }}
    secrets:
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  macos-oldrel-1:
    if: ${{ ! cancelled() }}
    needs: [config, ubuntu-oldrel-1]
    uses: ./.github/workflows/apps-test-os.yml
    with:
      r-version: ${{ needs.config.outputs.oldrel1 }}
      os: ${{ needs.config.outputs.macos }}
      cache-version: ${{ needs.config.outputs.cache-version }}
    secrets:
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  macos-oldrel-2:
    if: ${{ ! cancelled() }}
    needs: [config, ubuntu-oldrel-2]
    uses: ./.github/workflows/apps-test-os.yml
    with:
      r-version: ${{ needs.config.outputs.oldrel2 }}
      os: ${{ needs.config.outputs.macos }}
      cache-version: ${{ needs.config.outputs.cache-version }}
    secrets:
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  macos-oldrel-3:
    if: ${{ ! cancelled() }}
    needs: [config, ubuntu-oldrel-3]
    uses: ./.github/workflows/apps-test-os.yml
    with:
      r-version: ${{ needs.config.outputs.oldrel3 }}
      os: ${{ needs.config.outputs.macos }}
      cache-version: ${{ needs.config.outputs.cache-version }}
    secrets:
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  macos-oldrel-4:
    # TODO-future: re-enable this when R 3.6 is oldrel4
    # if: ${{ ! cancelled() }}
    if: false
    needs: [config, ubuntu-oldrel-4]
    uses: ./.github/workflows/apps-test-os.yml
    with:
      r-version: ${{ needs.config.outputs.oldrel4 }}
      os: ${{ needs.config.outputs.macos }}
      cache-version: ${{ needs.config.outputs.cache-version }}
    secrets:
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  ubuntu-release:
    needs: [precheck, config]
    uses: ./.github/workflows/apps-test-os.yml
    with:
      r-version: ${{ needs.config.outputs.release }}
      os: ${{ needs.config.outputs.ubuntu }}
      cache-version: ${{ needs.config.outputs.cache-version }}
    secrets:
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  ubuntu-oldrel-1:
    needs: [precheck, config]
    uses: ./.github/workflows/apps-test-os.yml
    with:
      r-version: ${{ needs.config.outputs.oldrel1 }}
      os: ${{ needs.config.outputs.ubuntu }}
      cache-version: ${{ needs.config.outputs.cache-version }}
    secrets:
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  ubuntu-oldrel-2:
    needs: [precheck, config]
    uses: ./.github/workflows/apps-test-os.yml
    with:
      r-version: ${{ needs.config.outputs.oldrel2 }}
      os: ${{ needs.config.outputs.ubuntu }}
      cache-version: ${{ needs.config.outputs.cache-version }}
    secrets:
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  ubuntu-oldrel-3:
    needs: [precheck, config]
    uses: ./.github/workflows/apps-test-os.yml
    with:
      r-version: ${{ needs.config.outputs.oldrel3 }}
      os: ${{ needs.config.outputs.ubuntu }}
      cache-version: ${{ needs.config.outputs.cache-version }}
    secrets:
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  ubuntu-oldrel-4:
    needs: [precheck, config]
    # TODO-future: re-enable this when R 3.6 is oldrel4
    if: false
    uses: ./.github/workflows/apps-test-os.yml
    with:
      r-version: ${{ needs.config.outputs.oldrel4 }}
      os: ${{ needs.config.outputs.ubuntu }}
      cache-version: ${{ needs.config.outputs.cache-version }}
    secrets:
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  windows-release:
    if: ${{ ! cancelled() }}
    needs: [config, macos-release]
    uses: ./.github/workflows/apps-test-os.yml
    with:
      r-version: ${{ needs.config.outputs.release }}
      os: ${{ needs.config.outputs.windows }}
      cache-version: ${{ needs.config.outputs.cache-version }}
    secrets:
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  windows-oldrel-1:
    if: ${{ ! cancelled() }}
    needs: [config, macos-oldrel-1]
    uses: ./.github/workflows/apps-test-os.yml
    with:
      r-version: ${{ needs.config.outputs.oldrel1 }}
      os: ${{ needs.config.outputs.windows }}
      cache-version: ${{ needs.config.outputs.cache-version }}
    secrets:
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  windows-oldrel-2:
    if: ${{ ! cancelled() }}
    needs: [config, macos-oldrel-2]
    uses: ./.github/workflows/apps-test-os.yml
    with:
      r-version: ${{ needs.config.outputs.oldrel2 }}
      os: ${{ needs.config.outputs.windows }}
      cache-version: ${{ needs.config.outputs.cache-version }}
    secrets:
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  windows-oldrel-3:
    if: ${{ ! cancelled() }}
    needs: [config, macos-oldrel-3]
    uses: ./.github/workflows/apps-test-os.yml
    with:
      r-version: ${{ needs.config.outputs.oldrel3 }}
      os: ${{ needs.config.outputs.windows }}
      cache-version: ${{ needs.config.outputs.cache-version }}
    secrets:
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  windows-oldrel-4:
    # TODO-future: re-enable this when R 3.6 is oldrel4
    # if: ${{ ! cancelled() }}
    if: false
    needs: [config, macos-oldrel-4]
    uses: ./.github/workflows/apps-test-os.yml
    with:
      r-version: ${{ needs.config.outputs.oldrel4 }}
      os: ${{ needs.config.outputs.windows }}
      cache-version: ${{ needs.config.outputs.cache-version }}
    secrets:
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  build-results:
    uses: ./.github/workflows/build-results.yml
    if: ${{ (! cancelled()) && (github.event_name != 'pull_request') }}
    needs:
      ## Comment for now to reduce requirements as we know the last round is windows
      # - macos-release
      # - macos-oldrel-1
      # - macos-oldrel-2
      # - macos-oldrel-3
      # - macos-oldrel-4

      # - ubuntu-release
      # - ubuntu-oldrel-1
      # - ubuntu-oldrel-2
      # - ubuntu-oldrel-3
      # - ubuntu-oldrel-4

      - windows-release
      - windows-oldrel-1
      - windows-oldrel-2
      - windows-oldrel-3
    # TODO-future: re-enable this when R 3.6 is oldrel4
    # - windows-oldrel-4
