on:
  push:
    branches:
      - _test_results

name: Build static site

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: '"Two workflows enter, one workflow leaves"'
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          all_but_latest: true

      - uses: actions/checkout@v2
        with:
          # Only need current files
          fetch-depth: 0

      - name: Git config
        shell: bash
        # set local email to actor
        # set local name to actor
        # set to merge when pulling (used for test results)
        # need to unset the extra header to allow for regular https push
        # display config
        run: |
          git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com" && \
            git config --local user.name "${GITHUB_ACTOR}" && \
            git config --local pull.rebase false && \
            git config --local --unset http.https://github.com/.extraheader && \
            git config --local --list

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: any::sessioninfo
          cache-version: site-1
          extra-packages: |
            any::dplyr
            any::tidyr
            any::lubridate
            any::jsonlite
            any::shiny
            any::progress
            any::rmarkdown
            any::bslib
            any::rlang
            any::DT
            any::withr
            any::fontawesome

      - name: Run `build_site.R`
        shell: Rscript {0}
        run: |
          source("build_site.R", echo = TRUE)

      - name: Commit and Push to git
        shell: bash
        run: |
          SHA="${{ github.sha }}"
          SHORT_SHA="${SHA:0:7}"

          git add site && \
            git commit -m "build site - rstudio/shinycoreci@$SHORT_SHA"
          COMMIT_RESULT=$?

          if [ $COMMIT_RESULT -eq 0 ]; then
            # attempt to push until success. Allow for 15 attempts
            COUNTER=0
            git pull origin _test_results
            until git push "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/rstudio/shinycoreci.git" _test_results
            do
              # wait 5-15 seconds to avoid deadlock
              sleep $[ ($RANDOM % 10) + 5 ]s
              [[ COUNTER -gt 15 ]] && echo "Too many attempts!" && exit 1
              ((COUNTER++))
              echo "Push failed. Trying again. Try #$COUNTER"
              # pull again to have the latest
              git pull origin _test_results
            done
          else
            echo "No changes to commit or push"
          fi
