on:
  workflow_call:
    inputs:
      extra-packages:
        type: string
        default: ""
        required: false
      cache-version:
        type: string
        default: "1"
        required: false
      pandoc-version:
        type: string
        default: "2.7.3"
        required: false
      check-title:
        type: boolean
        default: true
        required: false

name: pkgdown

jobs:
  pkgdown:

    runs-on: ubuntu-20.04
    env:
      GITHUB_PAT: ${{ github.token }}

    steps:
      - uses: actions/checkout@v2

      - uses: rstudio/shinycoreci/.github/actions/install-r-package@v1
        with:
          pandoc-version: ${{ inputs.pandoc-version }}
          cache-version: ${{ inputs.cache-version }}
          needs: website
          extra-packages: |
            pkgdown
            ${{ inputs.extra-packages }}

      - name: Verify reference (PR)
        if: github.event_name != 'push'
        shell: Rscript {0}
        run: |
          if ("${{inputs.check-title}}" == "false") options(rmarkdown.html_vignette.check_title = FALSE)
          pkgdown::build_site(new_process = FALSE)
          if (!require("testthat")) pak::pkg_install("testthat")
          testthat::expect_warning(
            pkgdown::build_reference_index(),
            NA
          )

      - name: Setup git (push)
        if: github.event_name == 'push'
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Build and deploy pkgdown site (push)
        if: github.event_name == 'push'
        shell: Rscript{0}
        run: |
          if ("${{inputs.check-title}}" == "false") options(rmarkdown.html_vignette.check_title = FALSE)
          pkgdown::deploy_to_branch(new_process = FALSE)
