on:
  push:
    branches: [main, rc-**]
  pull_request:
    branches: [main]

name: Package Checks

jobs:
  # pkgdown:
  #   uses: rstudio/shinycoreci/.github/workflows/call-pkgdown.yaml@v1
  Rituals:
    uses: rstudio/shinycoreci/.github/workflows/call-rituals.yaml@v1
  R-CMD-check:
    uses: rstudio/shinycoreci/.github/workflows/call-R-CMD-check.yaml@v1
    with:
      release-only: true

  # shinycoreci specific testing
  validate-remotes:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: rstudio/shinycoreci/.github/composite/install-r-package@v1
      - name: Validate remotes order
        shell: Rscript {0}
        run: |
          testthat::expect_error({
            shinycoreci:::validate_remotes_order()
          }, NA)
